// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgPN3vFJnxhKQTfMBgJs2EiVkXjWWBU2s',
    appId: '1:623857881205:web:f406f7c4c0ef1acd82a83c',
    messagingSenderId: '623857881205',
    projectId: 'md2022-1d718',
    authDomain: 'md2022-1d718.firebaseapp.com',
    storageBucket: 'md2022-1d718.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfQjFyIx8ZpcorgJedihqBnrywWQUIOnE',
    appId: '1:623857881205:android:22f330e08e4896ba82a83c',
    messagingSenderId: '623857881205',
    projectId: 'md2022-1d718',
    storageBucket: 'md2022-1d718.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDi0dDLURMQXvd5VDuiPxKSWa0_PYZMu1k',
    appId: '1:623857881205:ios:03015f2760ca6ef282a83c',
    messagingSenderId: '623857881205',
    projectId: 'md2022-1d718',
    storageBucket: 'md2022-1d718.appspot.com',
    iosClientId: '623857881205-h2p3a1ofov5u1toralv8p1rtam0aan71.apps.googleusercontent.com',
    iosBundleId: 'com.example.helloFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDi0dDLURMQXvd5VDuiPxKSWa0_PYZMu1k',
    appId: '1:623857881205:ios:03015f2760ca6ef282a83c',
    messagingSenderId: '623857881205',
    projectId: 'md2022-1d718',
    storageBucket: 'md2022-1d718.appspot.com',
    iosClientId: '623857881205-h2p3a1ofov5u1toralv8p1rtam0aan71.apps.googleusercontent.com',
    iosBundleId: 'com.example.helloFirebase',
  );
}
